### PR TITLE
Port the BSP to the imxrt-rs HAL

### PR DESCRIPTION
**Pull request by mciantyre**
The PR demonstrates the changes necessary to support the imxrt-rs HAL in the Teensy 4 BSP. It disables the HAL and PAC crates in this repository's workspace, and it updates the BSP to use the alternative HAL. There were some name changes and an PWM API change introduced in the HAL, and the BSP and Teensy 4 examples account for these changes.

See imxrt-rs/imxrt-rs#24 to give it a try.

### CODE REVIEW

**Comment by mciantyre** [comment]
Draft PR, as it requires a local copy of the imxrt-rs HAL. See the BSP's `Cargo.toml` and clone the `imxrt-hal` repository at the linked PR if you'd like to give this a try before it's merged.

**Comment by bfrog** [comment]
So far so good from what I can tell, examples build for me, need to install and figure out the teensy cli stuff, will try today

**Comment by bfrog** [comment]
I can confirm the pit, led, and timer examples worked for me. I couldn't get the uart example working though perhaps I was looking at the wrong pins on the teensy. Will try some more hopefully tonight!

**Comment by bfrog** [comment]
I attempted to test the uart today, it looks like the clocks aren't quite setup right. This might be easier to debug on the evk, so I'll spend some time today trying to set that up and port the examples

**Comment by mciantyre** [comment]
Thanks for giving it a test!

What kind of issues are you seeing with the UART clocks? Anything I might reproduce?

Attached images show my measurements at `9600` and `115200` baud rates. I'm measuring the expected `~104us` and `~8.7us` periods for each respective baud rate. Is that giving you trouble?

9600bps:
9600baud

115200bps:
115200baud

**Comment by bfrog** [comment]
Hmmm yeah your logic analyzer looks right, I was trying my scope decoder, will look closer again.

**Comment by mciantyre** [comment]
Will be released on the 0.2.0 version of imxrt-hal (imxrt-rs/imxrt-rs#41).

**Comment by mciantyre** [comment]
`teensy4-bsp` incorporates the 0.2.1 version of the `imxrt-hal` HAL; see imxrt-rs/imxrt-rs#44.

**Pull request merged**
